// server.js
import express from "express";
import cors from "cors";
import bodyParser from "body-parser";
import fetch from "node-fetch";

const app = express();
app.use(cors());
app.use(bodyParser.json());

// ✅ AI Tutor endpoint
app.post("/api/ask", async (req, res) => {
  const { question, subject } = req.body;

  if (!question) {
    return res.status(400).json({ answer: "Please ask a valid question." });
  }

  try {
    // Example logic — replace this section with your real AI API call (OpenAI, Gemini, etc.)
    // For now, it simulates a response based on the question.
    const responseText = `The answer to "${question}" in ${subject} is currently generated by Akin S. Sokpah's AI Tutor.`;

    res.json({ answer: responseText });
  } catch (error) {
    console.error("AI Error:", error);
    res.status(500).json({ answer: "⚠️ Error generating AI response." });
  }
});

app.get("/", (req, res) => {
  res.send("🧠 FullTask AI Tutor backend is running successfully!");
});

const PORT = process.env.PORT || 10000;
app.listen(PORT, () => console.log(`✅ Server running on port ${PORT}`));
