// backend/server.js
import express from "express";
import cors from "cors";
import fetch from "node-fetch";

const app = express();
app.use(cors());
app.use(express.json());

const PORT = process.env.PORT || 3000;

// Root endpoint
app.get("/", (req, res) => {
  res.send("🧠 FullTask AI Backend running successfully!");
});

// AI tutor route
app.post("/api/ask", async (req, res) => {
  try {
    const { question } = req.body;
    if (!question) return res.status(400).json({ error: "No question provided" });

    // Simulate AI response
    const fakeAnswer = `The answer to "${question}" is currently generated by Akin S. Sokpah's AI Tutor.`;

    res.json({ answer: fakeAnswer });
  } catch (err) {
    console.error("Error:", err);
    res.status(500).json({ error: "Server error" });
  }
});

app.listen(PORT, () => console.log(`✅ FullTask AI Backend running on port ${PORT}`));
app.post("/api/ask", async (req, res) => {
  const { question, subject } = req.body;
  res.json({ answer: `The answer to "${question}" is currently generated by Akin S. Sokpah's AI Tutor.` });
});
